const produtos = [
    // --- BORDADOS ---
    { id: 1, categoria: "Bordados", patente: "sd", titulo: "Curso de SD", preco: 8.0, imagem: "" },
    { id: 2, categoria: "Bordados", patente: "sgt", titulo: "Curso de SGT", preco: 8.0, imagem: "" },
    { id: 3, categoria: "Bordados", patente: "geral", titulo: "Curso CAIS", preco: 8.0, imagem: "" },
    { id: 4, categoria: "Bordados", patente: "geral", titulo: "Bandeira Paulista Bordada", preco: 10.0, imagem: "" },
    { id: 5, categoria: "Bordados", patente: "geral", titulo: "Targeta operacional", preco: 8.0, personalizavel: true, imagem: "" },
    { id: 6, categoria: "Bordados", patente: "geral", titulo: "Targeta ed fisica", preco: 8.0, personalizavel: true, imagem: "" },

    // --- EMBORRACHADOS / ACESSÓRIOS ---
    { id: 7, categoria: "Emborrachados", patente: "geral", titulo: "Listel", preco: 20.0, imagem: "" },
    { id: 8, categoria: "Emborrachados", patente: "geral", titulo: "Logo Colorido", preco: 20.0, imagem: "" },
    { id: 9, categoria: "Emborrachados", patente: "geral", titulo: "Polícia Militar Emborrachado (Costas)", preco: 30.0, imagem: "" },
    { id: 10, categoria: "Emborrachados", patente: "geral", titulo: "Láureas de Garrafão Emborrachados", preco: 20.0, imagem: "" },
    { id: 11, categoria: "Emborrachados", patente: "geral", titulo: "Cursos Emborrachados", preco: 20.0, imagem: "" },
    { id: 12, categoria: "Emborrachados", patente: "geral", titulo: "Patrulheiro Emborrachado", preco: 20.0, imagem: "" },
    { id: 13, categoria: "Emborrachados", patente: "geral", titulo: "Direção Defensiva", preco: 20.0, imagem: "" },
    { id: 14, categoria: "Emborrachados", patente: "geral", titulo: "Trânsito Urbano", preco: 20.0, imagem: "" },
    { id: 15, categoria: "Emborrachados", patente: "geral", titulo: "Bandeira Paulista Emborrachada", preco: 20.0, imagem: "" },
    { id: 16, categoria: "Emborrachados", patente: "geral", titulo: "Brasões dos Batalhões Emborrachados", preco: 30.0, imagem: "" },
    { id: 17, categoria: "Emborrachados", patente: "sd", titulo: "Divisa Emborrachada (Colete Modular) - SD", preco: 20.0, imagem: "" },
    { id: 18, categoria: "Emborrachados", patente: "cb", titulo: "Divisa Emborrachada (Colete Modular) - CB", preco: 20.0, imagem: "" },
    { id: 19, categoria: "Emborrachados", patente: "sgt", titulo: "Divisa Emborrachada (Colete Modular) - 3º SGT", preco: 20.0, imagem: "" },
    { id: 20, categoria: "Emborrachados", patente: "sgt", titulo: "Divisa Emborrachada (Colete Modular) - 2º SGT", preco: 20.0, imagem: "" },
    { id: 21, categoria: "Emborrachados", patente: "sgt", titulo: "Divisa Emborrachada (Colete Modular) - 1º SGT", preco: 20.0, imagem: "" },
    { id: 22, categoria: "Emborrachados", patente: "sd", titulo: "Divisa para Gandola (Emborrachada) - SD", preco: 5.0, imagem: "" },
    { id: 23, categoria: "Emborrachados", patente: "cb", titulo: "Divisa para Gandola (Emborrachada) - CB", preco: 5.0, imagem: "" },
    { id: 24, categoria: "Emborrachados", patente: "sgt", titulo: "Divisa para Gandola (Emborrachada) - 3º SGT", preco: 5.0, imagem: "" },
    { id: 25, categoria: "Emborrachados", patente: "sgt", titulo: "Divisa para Gandola (Emborrachada) - 2º SGT", preco: 5.0, imagem: "" },
    { id: 26, categoria: "Emborrachados", patente: "sgt", titulo: "Divisa para Gandola (Emborrachada) - 1º SGT", preco: 5.0, imagem: "" },
    { id: 27, categoria: "Emborrachados", patente: "sgt", titulo: "Divisa para Gandola (Emborrachada) - Sub-Tenente", preco: 5.0, imagem: "" },
    { id: 28, categoria: "Emborrachados", patente: "geral", titulo: "Divisa para Gandola (Emborrachada) - Bucaneiro", preco: 5.0, imagem: "" },
    { id: 29, categoria: "Emborrachados", patente: "geral", titulo: "Divisa para Gandola (Emborrachada) - Bomboneiro", preco: 5.0, imagem: "" },

    // --- UNIFORMES ---
    { id: 30, categoria: "Uniformes", patente: "geral", titulo: "Agasalho", preco: 120.0, tamanho: true, imagem: "" },
    { id: 31, categoria: "Uniformes", patente: "geral", titulo: "Camisetas Ed física", preco: 32.0, tamanho: true, imagem: "" },
    { id: 32, categoria: "Uniformes", patente: "geral", titulo: "Camisetas cinzas", preco: 40.0, tamanho: true, imagem: "" },
    { id: 33, categoria: "Uniformes", patente: "geral", titulo: "Shorts Ed física", preco: 30.0, tamanho: true, imagem: "" },
    { id: 34, categoria: "Uniformes", patente: "geral", titulo: "Shorts térmico", preco: 30.0, tamanho: true, imagem: "" },
    { id: 35, categoria: "Uniformes", patente: "geral", titulo: "Sunga box", preco: 40.0, tamanho: true, imagem: "" },

    // --- ACESSÓRIOS ---
    { id: 36, categoria: "Acessórios", patente: "geral", titulo: "Faixa refletiva", preco: 25.0, imagem: "" },
    { id: 37, categoria: "Acessórios", patente: "geral", titulo: "Coldre da DM", preco: 100.0, imagem: "" },
    { id: 38, categoria: "Acessórios", patente: "geral", titulo: "Carregador da Bélica de polímero", preco: 120.0, imagem: "" },
    { id: 39, categoria: "Acessórios", patente: "geral", titulo: "Porta carregador de fuzil", preco: 75.0, imagem: "" },
    { id: 40, categoria: "Acessórios", patente: "geral", titulo: "Capa modular", preco: 520.0, imagem: "" },
    { id: 41, categoria: "Acessórios", patente: "geral", titulo: "Adaptador de perna para o coldre da PM", preco: 55.0, imagem: "" },
    { id: 42, categoria: "Acessórios", patente: "geral", titulo: "Bandoleira", preco: 50.0, imagem: "" }, // <--- Alterado aqui (removido o tamanho: true)
    { id: 43, categoria: "Acessórios", patente: "geral", titulo: "Lanterna USB", preco: 35.0, imagem: "" },
    { id: 44, categoria: "Acessórios", patente: "geral", titulo: "Abafador auricular", preco: 30.0, imagem: "" },
    { id: 45, categoria: "Acessórios", patente: "geral", titulo: "Alicate multiuso", preco: 45.0, imagem: "" },
    { id: 46, categoria: "Acessórios", patente: "geral", titulo: "Faca padrão da polícia (Modelo 1)", preco: 50.0, imagem: "" },
    { id: 47, categoria: "Acessórios", patente: "geral", titulo: "Faca padrão da polícia (Modelo 2)", preco: 60.0, imagem: "" },
    { id: 48, categoria: "Acessórios", patente: "geral", titulo: "Verniz (250ml)", preco: 40.0, imagem: "" },
    { id: 49, categoria: "Acessórios", patente: "geral", titulo: "Verniz (100ml)", preco: 25.0, imagem: "" },
    { id: 50, categoria: "Acessórios", patente: "geral", titulo: "Graxa", preco: 40.0, imagem: "" },
    { id: 51, categoria: "Acessórios", patente: "geral", titulo: "Kit escova de sapato", preco: 25.0, imagem: "" },
    { id: 52, categoria: "Acessórios", patente: "geral", titulo: "Cadeado de segredo", preco: 30.0, imagem: "" },
    { id: 53, categoria: "Acessórios", patente: "geral", titulo: "Cadeado de chave", preco: 30.0, imagem: "" },
    { id: 54, categoria: "Acessórios", patente: "geral", titulo: "Organizador de armário", preco: 50.0, imagem: "" },
    { id: 55, categoria: "Acessórios", patente: "geral", titulo: "Transportador de farda", preco: 50.0, imagem: "" },
    { id: 56, categoria: "Acessórios", patente: "geral", titulo: "Prancheta personalizada", preco: 60.0, imagem: "" },
    { id: 57, categoria: "Acessórios", patente: "geral", titulo: "Elástico de prancheta personalizada", preco: 15.0, imagem: "" },
    { id: 58, categoria: "Acessórios", patente: "geral", titulo: "Priscila (Emborrachada ou Pano)", preco: 20.0, imagem: "" },
    { id: 59, categoria: "Acessórios", patente: "geral", titulo: "Touca de natação", preco: 20.0, imagem: "" }
];